'use client';
import {useEffect,useMemo,useState} from 'react';

type Article={id:string;source:string;sourceId:string;title:string;titleZh?:string;description:string;descriptionZh?:string;translationStatus?:string;translationError?:string;topic?:string;url:string;publishedAt:string;sentiment:string;analysisMode:string;summaryZh:string;claim:string;verificationPoints?:string[];recommendations?:{label:string;url:string;action:string}[];checks:string[];importance:number;crossSourceCount:number;cluster:string};
type Status={id:string;name:string;ok:boolean;fetched:number;matched:number;error?:string};
type Report={date:string;generatedAt:string;windowStart:string;windowEnd:string;complete:boolean;mode:string;articles:Article[];statuses:Status[]};
type Source={id:string;name:string;region:string;url:string};
type Dashboard={report:Report|null;reports:{date:string;count:number}[];lastRun:{status:string}|null;sources:Source[]};
const sourceZh:Record<string,string>={bbc:'英国广播公司',guardian:'卫报',washpost:'华盛顿邮报',aljazeera:'半岛电视台',dw:'德国之声',france24:'法国24电视台',euronews:'欧洲新闻台',npr:'美国国家公共电台',ft:'金融时报',nikkei:'日经亚洲',nyt:'纽约时报',scmp:'南华早报',sky:'天空新闻台',voa:'美国之音',cbc:'加拿大广播公司',conversation:'对话网'};
const time=(s:string)=>new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(s));
const link=(s:string)=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch{return '#'}};
const headline=(a:Article)=>a.titleZh||a.title;
const excerpt=(a:Article)=>a.descriptionZh||a.description||'该 RSS 条目未提供摘要。';
const needsCheck=(a:Article)=>!!(a.verificationPoints?.length||a.claim&&!a.claim.startsWith('未从'));

export default function Home(){
 const [data,setData]=useState<Dashboard|null>(null),[tab,setTab]=useState<'overview'|'checks'|'sources'>('overview'),[date,setDate]=useState(''),[q,setQ]=useState(''),[source,setSource]=useState('all'),[tone,setTone]=useState('all'),[topic,setTopic]=useState('all'),[sort,setSort]=useState('importance'),[selected,setSelected]=useState<Article|null>(null),[running,setRunning]=useState(false),[progress,setProgress]=useState<{stage:string;message:string}[]>([]),[error,setError]=useState(''),[translationNote,setTranslationNote]=useState('');
 async function load(chosen=''){try{const r=await fetch('/api/dashboard'+(chosen?'?date='+encodeURIComponent(chosen):''),{cache:'no-store'});const body=await r.json() as Dashboard&{error?:string};if(!r.ok)throw Error(body.error||'数据读取失败');setData(body);setError('')}catch(e){setError(e instanceof Error?e.message:'数据读取失败')}}
 useEffect(()=>{void load()},[]);
 useEffect(()=>{if(!selected)return;const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setSelected(null)};document.addEventListener('keydown',onKey);return ()=>document.removeEventListener('keydown',onKey)},[selected]);
 async function run(){if(running)return;setRunning(true);setProgress([]);setError('');try{const res=await fetch('/api/run',{method:'POST'});if(!res.ok||!res.body)throw Error('执行失败 HTTP '+res.status);const reader=res.body.getReader(),decoder=new TextDecoder();let buffer='',finished=false;while(true){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});let split;while((split=buffer.indexOf('\n\n'))>=0){const frame=buffer.slice(0,split);buffer=buffer.slice(split+2);const event=frame.match(/^event: (.+)$/m)?.[1],line=frame.match(/^data: (.+)$/m)?.[1];if(!line)continue;const payload=JSON.parse(line);if(event==='progress')setProgress(p=>[...p,{stage:payload.stage,message:payload.message}]);if(event==='error')throw Error(payload.message);if(event==='done'){finished=true;setProgress(p=>[...p,{stage:'done',message:'已保存 '+payload.count+' 条报道至 '+payload.date+' 报告'}]);setDate('');await load()}}}if(!finished)throw Error('连接已结束，未收到完成状态')}catch(e){setError(e instanceof Error?e.message:'任务失败')}finally{setRunning(false)}}
 async function chooseDate(next:string){setDate(next);await load(next)}
 const report=data?.report,all=report?.articles||[],sources=data?.sources||[];
 async function saveTranslation(e:React.FormEvent<HTMLFormElement>){
   e.preventDefault();if(!selected||!report)return;
   const values=new FormData(e.currentTarget),titleZh=String(values.get('titleZh')||'').trim(),descriptionZh=String(values.get('descriptionZh')||'').trim();
   if(!/[\u3400-\u9fff]/.test(titleZh)||selected.description&&!/[\u3400-\u9fff]/.test(descriptionZh)){setTranslationNote('请填写标题与摘要的中文对照。');return;}
   try{const response=await fetch('/api/translations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({date:report.date,items:[{id:selected.id,titleZh,descriptionZh}]})});if(!response.ok)throw Error('保存失败 HTTP '+response.status);
     const updated={...selected,titleZh,descriptionZh,translationStatus:selected.description?'已翻译':'无摘要',translationError:undefined,summaryZh:selected.analysisMode==='AI'&&selected.summaryZh?selected.summaryZh:descriptionZh};
     setSelected(updated);setData(current=>current?.report?.date===report.date?{...current,report:{...current.report,articles:current.report.articles.map(x=>x.id===updated.id?updated:x)}}:current);setTranslationNote('中文对照已保存。');
   }catch(err){setTranslationNote(err instanceof Error?err.message:'保存失败')}
 }
 const articles=useMemo(()=>all.filter(a=>(tab!=='checks'||needsCheck(a))&&(source==='all'||a.sourceId===source)&&(tone==='all'||a.sentiment===tone)&&(topic==='all'||(a.topic||'其他')===topic)&&(!q||[a.title,a.titleZh,a.description,a.descriptionZh,a.summaryZh,a.source,a.claim].join(' ').toLowerCase().includes(q.toLowerCase()))).sort((a,b)=>sort==='time'?Date.parse(b.publishedAt)-Date.parse(a.publishedAt):sort==='cross'?b.crossSourceCount-a.crossSourceCount:b.importance-a.importance),[all,tab,source,tone,topic,q,sort]);
 const clusters=useMemo(()=>{const map=new Map<string,Article[]>();for(const a of all){const k=a.cluster||a.id;map.set(k,[...(map.get(k)||[]),a])}return [...map.values()].sort((a,b)=>Math.max(...b.map(x=>x.importance))-Math.max(...a.map(x=>x.importance))).slice(0,5)},[all]);
 const checks=all.filter(needsCheck).length,negative=all.filter(a=>a.sentiment==='负面').length;
 return <div className="shell"><aside className="sidebar"><div className="brand"><strong>真探</strong><small>TRUTHSEEKER</small></div><div className="nav-caption">INTELLIGENCE DESK</div><nav><button className={tab==='overview'?'nav active':'nav'} onClick={()=>setTab('overview')}><span>▦</span> 每日舆情</button><button className={tab==='checks'?'nav active':'nav'} onClick={()=>setTab('checks')}><span>◇</span> 核查线索 <em>{checks}</em></button><button className={tab==='sources'?'nav active':'nav'} onClick={()=>setTab('sources')}><span>◉</span> 媒体信源 <em>{sources.length}</em></button></nav><div className="side-bottom"><p className="internal-only">该网站仅限真探工作室（TruthSeeker）内部使用</p></div></aside>
 <main className="main"><header className="topbar"><span>真探 TruthSeeker <b>/</b> 国际新闻监测</span></header><div className="content">
 <div className="hero"><div className="hero-copy"><div className="eyebrow">TRUTHSEEKER / GLOBAL CHINA WATCH <span className="hero-index">01 — {sources.length}</span></div><h1>在这里瞭望世界，<br/><span>在这里探索真相</span></h1><p>{sources.length} 家媒体 · RSS 滚动采集 · 采集后英中对照入库 · 核查选题工作台</p><div className="hero-actions"><button className="primary" onClick={run} disabled={running}>{running?'正在运行…':'立即运行监测'}</button><span>08:00 CST / 每日自动归档</span></div></div><div className="hero-orbit" aria-hidden="true"><div className="orbit one"/><div className="orbit two"/><div className="orbit three"/><div className="globe">真</div><span className="orb-label a">MONITOR / 监测</span><span className="orb-label b">VERIFY / 核查</span></div></div>
 {error&&<div className="alert error" role="alert">{error}</div>}
 {(running||progress.length>0)&&<section className="progress-panel" aria-live="polite"><div className="progress-header"><span className={running?'spinner':''}>↻</span><strong>{running?'监测任务正在执行':'本轮监测已完成'}</strong><small>采集 → 去重 → 研判 → 翻译 → 排序 → 入库</small></div><div className="progress-list">{progress.map((p,i)=><div key={i}><span>{String(i+1).padStart(2,'0')}</span><b>{p.stage}</b><p>{p.message}</p></div>)}</div></section>}
 <section className="report-head"><div><div className="eyebrow">DAILY REPORT</div><h2>每日监测报告</h2><p>{report?time(report.windowStart)+' — '+time(report.windowEnd)+' · '+(report.complete?'完整日报':'进行中快照'):'尚未生成报告，点击“立即运行监测”获取真实 RSS 条目。'}</p></div><div className="report-controls"><select value={date||report?.date||''} onChange={e=>chooseDate(e.target.value)} aria-label="历史报告日期"><option value="" disabled>选择报告日期</option>{(data?.reports||[]).map(r=><option value={r.date} key={r.date}>{r.date} · {r.count} 条</option>)}</select><small>最近生成：{report?time(report.generatedAt):'—'}</small></div></section>
 <div className="metrics"><div><span>收录报道</span><strong>{report?.articles.length??'—'}</strong><small>标题或摘要含关键词</small></div><div><span>待核查线索</span><strong>{report?checks:'—'}</strong><small>仅作选题提示</small></div><div><span>负面语境</span><strong>{report?negative:'—'}</strong><small>倾向不代表失实</small></div><div><span>信源成功</span><strong>{report?report.statuses.filter(s=>s.ok).length+'/'+sources.length:'—'}</strong><small>逐站状态见媒体信源</small></div></div>
 <div className="mode-note"><span>ⓘ</span><p>{report?.mode==='AI'?'模型辅助研判，仍需人工复核。':'倾向、话题和核查线索为规则初筛；未配置模型时不生成虚假定论。'} 翻译在采集阶段入库，页面直接读取已存内容。免费翻译服务有限额，失败项会自动重试；RSS 只覆盖当前订阅条目及标题摘要，不保证收齐媒体全部报道或全文。{translationNote&&<strong className="translation-note"> {translationNote}</strong>}</p></div>
 {tab==='sources'?<section className="panel source-panel"><div className="panel-heading"><div><div className="eyebrow">SOURCE HEALTH</div><h2>{sources.length} 个监测信源</h2></div><p>免费 RSS 可用性及逐站入选报道</p></div><div className="source-grid">{sources.map(s=>{const st=report?.statuses.find(x=>x.id===s.id),outlet=all.filter(a=>a.sourceId===s.id);return <article className="source-card" key={s.id}><div><div className="source-icon">{s.name.slice(0,2).toUpperCase()}</div><span className={st?.ok?'source-state ok':st?'source-state fail':'source-state'}>{st?.ok?'● 正常':st?'● 失败':'○ 待运行'}</span></div><h3>{sourceZh[s.id]||s.name}</h3><p>{s.name} · {s.region}</p><div className="source-numbers"><span>读取 <b>{st?.fetched??'—'}</b></span><span>入选 <b>{outlet.length}</b></span></div>{st?.error&&<small className="source-error">{st.error}</small>}<div className="source-highlights">{outlet.slice(0,2).map(a=><button key={a.id} onClick={()=>setSelected(a)}>{headline(a)}<small lang="en">{a.title}</small></button>)}{outlet.length===0&&<small>本轮无关键词命中报道</small>}</div><button className="source-view" onClick={()=>{setSource(s.id);setTab('overview')}}>查看该媒体报道</button><a href={link(s.url)} target="_blank" rel="noopener noreferrer">查看 RSS 源</a></article>})}</div></section>:<>
 {tab==='overview'&&<section className="trend-section"><div className="section-heading"><div><div className="eyebrow">CROSS-OUTLET SIGNALS</div><h2>重点话题榜</h2></div><span>按时效与跨站提及排序</span></div><div className="trends">{clusters.length?clusters.map((group,i)=><button key={group[0].cluster} className="trend" onClick={()=>setSelected(group[0])}><span className="trend-rank">{String(i+1).padStart(2,'0')}</span><div><span className="topic-kicker">{group[0].topic||'其他'} / TOPIC</span><strong>{headline(group[0])}</strong>{group[0].titleZh&&<span className="trend-en" lang="en">{group[0].title}</span>}<small>{group[0].source} · {group[0].crossSourceCount} 家信源相近话题</small></div><div className="trend-score">{group[0].importance}<small>优先分</small></div></button>):<div className="empty">运行监测后将在此展示真实报道话题。</div>}</div></section>}
 <section className="panel list-panel"><div className="panel-heading"><div><div className="eyebrow">{tab==='checks'?'VERIFICATION QUEUE':'ARTICLE STREAM'}</div><h2>{tab==='checks'?'待核查信息点':'涉华报道聚合'}</h2></div><span>{articles.length} 条结果</span></div><div className="filters"><label className="search"><span>⌕</span><input value={q} onChange={e=>setQ(e.target.value)} placeholder="搜索中英文标题、摘要、信源"/></label><select value={source} onChange={e=>setSource(e.target.value)} aria-label="筛选媒体"><option value="all">全部媒体</option>{sources.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><select value={topic} onChange={e=>setTopic(e.target.value)} aria-label="筛选话题"><option value="all">全部话题</option>{['军事','时政','社会','经济','科技','环境','体育','文化','其他'].map(x=><option key={x}>{x}</option>)}</select><select value={tone} onChange={e=>setTone(e.target.value)} aria-label="筛选倾向"><option value="all">全部倾向</option><option value="负面">负面</option><option value="中性">中性</option><option value="正面">正面</option></select><select value={sort} onChange={e=>setSort(e.target.value)} aria-label="排序"><option value="importance">重要性排序</option><option value="time">最新发布</option><option value="cross">跨站提及</option></select></div><div className="article-list">{articles.length?articles.map(a=><article className="article" key={a.id}><div className="article-side"><span className="source-mini">{sourceZh[a.sourceId]||a.source}</span><time>{time(a.publishedAt)} 北京时间</time></div><div className="article-body"><button className="article-title" onClick={()=>setSelected(a)}><strong>{headline(a)}</strong>{a.titleZh&&<span lang="en">{a.title}</span>}</button><div className="bilingual-summary"><p>{excerpt(a)}</p>{a.descriptionZh&&a.description&&<p className="english-copy" lang="en">{a.description}</p>}</div><div className="article-tags"><span className="tag topic">{a.topic||'其他'}</span><span className={a.sentiment==='负面'?'tag negative':a.sentiment==='正面'?'tag positive':'tag'}>{a.sentiment}语境</span>{needsCheck(a)&&<span className="tag check">核查线索</span>}{a.translationStatus==='翻译失败'&&<span className="tag negative" title={a.translationError}>译文异常</span>}<span className="tag plain">跨站 {a.crossSourceCount}</span></div></div><div className="article-actions"><div><b>{a.importance}</b><small>优先分</small></div><button onClick={()=>setSelected(a)} aria-label={'查看 '+a.title+' 详情'}>›</button></div></article>):<div className="empty">{report?'此日期和筛选条件下没有符合的报道。':'尚无日报。运行监测后将显示真实新闻。'}</div>}</div></section>
 </>}
 <footer><span>TruthSeeker · 国际新闻监测系统</span><small>由Jennifer Zhan开发</small></footer>
 </div></main>
 {selected&&<div className="overlay" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><aside className="drawer" role="dialog" aria-modal="true" aria-label="报道详情"><div className="drawer-top"><div className="eyebrow">ARTICLE / SOURCE TRACE</div><button onClick={()=>setSelected(null)} aria-label="关闭详情">×</button></div><div className="detail-number">{selected.topic||'其他'} / {selected.importance} PRIORITY</div><h2>{headline(selected)}</h2>{selected.titleZh&&<p className="detail-en" lang="en">{selected.title}</p>}<div className="drawer-meta"><strong>{sourceZh[selected.sourceId]||selected.source}</strong> / {selected.source} <span>·</span> {time(selected.publishedAt)} 北京时间</div><div className="drawer-tags"><span>{selected.topic||'其他'}</span><span>{selected.sentiment}语境</span><span>{selected.analysisMode}</span><span>{selected.crossSourceCount} 家相近话题信源</span></div><a className="original" href={link(selected.url)} target="_blank" rel="noopener noreferrer">打开媒体原文</a><div className="drawer-warning">本站保存 RSS 标题与摘要的英中对照，不包含媒体全文。{selected.translationStatus==='翻译失败'?'译文服务异常：'+(selected.translationError||'稍后重试')+'。':''} 倾向与待核查信息点需要结合原文和一手资料人工复核。</div>
 <section className="parallel"><h3>新闻报道摘要 · 英中对照</h3><div className="parallel-block"><small>中文</small><p>{selected.descriptionZh||selected.description||'该 RSS 条目未提供摘要。'}</p></div>{selected.descriptionZh&&selected.description&&<div className="parallel-block original-copy"><small>ENGLISH / RSS EXCERPT</small><p lang="en">{selected.description}</p></div>}</section>
 <section className="parallel"><h3>涉华内容表述 · RSS 摘录</h3><div className="parallel-block"><small>中文</small><p>{selected.descriptionZh||selected.titleZh||selected.description||selected.title}</p></div><div className="parallel-block original-copy"><small>ENGLISH / ORIGINAL FEED TEXT</small><p lang="en">{selected.description||selected.title}</p></div><p className="analysis-note">自动分析：{selected.analysisMode==='AI'?selected.claim:'以上为标题或摘要层面的规则初筛。是否存在失实或遗漏，须进一步核对报道全文。'}</p></section>
 {selected.summaryZh&&selected.summaryZh!==selected.descriptionZh&&<section><h3>中文精简摘要</h3><p>{selected.summaryZh}</p></section>}
 <section><h3>待核查信息点</h3><ul>{(selected.verificationPoints?.length?selected.verificationPoints:[selected.claim||'RSS 摘录未列出可直接核查的具体断言，请先核对媒体全文。']).map((x,i)=><li key={i}>{x}</li>)}</ul></section>
 <section><h3>核查建议</h3>{selected.recommendations?.length?<ul>{selected.recommendations.map((x,i)=><li key={i}>{x.action} <a href={link(x.url)} target="_blank" rel="noopener noreferrer">{x.label} ↗</a></li>)}</ul>:<ul><li>先打开<a href={link(selected.url)} target="_blank" rel="noopener noreferrer">媒体原文</a>核对完整引语、数据及原始链接，再检索当事方公开声明。</li></ul>}</section>
 <section className="translation-editor"><details><summary>校订已存中文译文</summary><form onSubmit={saveTranslation}><label>中文标题<input name="titleZh" required defaultValue={selected.titleZh||''} placeholder="输入与原文对应的中文标题"/></label><label>中文摘要<textarea name="descriptionZh" required={!!selected.description} defaultValue={selected.descriptionZh||''} rows={4} placeholder="输入与 RSS 原文对应的中文摘要"/></label><button type="submit">保存到日报</button></form></details></section>
 <section><h3>相近报道</h3>{all.filter(x=>x.id!==selected.id&&x.cluster===selected.cluster).slice(0,4).map(x=><a className="related" key={x.id} href={link(x.url)} target="_blank" rel="noopener noreferrer"><strong>{x.source} · {headline(x)} ↗</strong><span lang="en">{x.title}</span></a>)}{selected.crossSourceCount===1&&<p>当前快照暂无其他信源的相近标题；这不代表事件未被报道。</p>}</section></aside></div>}
 </div>;
}
